name: Check pull request

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup fvm
        uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      
      - name: Run flutter version
        run: flutter --version

      - name: Run pub get
        run: flutter pub get

      - name: Run analyze
        shell: bash
        run: flutter analyze | tee ./flutter_analyze_report.txt

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        if: always()
        with:
          ruby-version: '3.3'
          bundler-cache: true
      
      - name: Setup danger
        uses: MeilCli/danger-action@v5
        if: always()
        with:
          plugins_file: '.github/Gemfile'
          danger_file: '.github/Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
