name: Check pull request

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup fvm
        uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      
      - name: Run flutter version
        run: flutter --version

      - name: Run pub get
        run: flutter pub get

      - name: Run analyze
        shell: bash
        run: flutter analyze | tee ./flutter_analyze_report.txt
